PAGE_SIZE = 0x1000 # 4 KiB

# Bit flags used to indicate how a page should be mapped.
EXECUTABLE_FLAG = 1
WRITABLE_FLAG = 2
READABLE_FLAG = 4


SCHEDULING_TYPE_ID = 0
CHANNEL_TYPE_ID = 1
MEMORY_REGION_TYPE_ID = 2
IRQ_TYPE_ID = 3



